name = "Algos"
uuid = "3cc80ddc-a67c-4e93-965c-2eaab6133d87"
authors = ["Aidan Bailey"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
